### ISSUE TITLE
Detailed Runsheet / Script for: Migrate a Local SQL Database to Azure

### ISSUE THREAD

**Issue by kphillpotts** [Krumelur/RealEstate#15]
Script out how we will teach the session.
Do a run through and get timings
Work out exactly what resources / links we need for the session
Work out demos / activities and document

**Comment by Krumelur** [comment]
## Classify your data
### Unstructured
### Semi-sctructured
### Structured

## Store relational data on Azure
### Choose the appropriate Azure SQL option
* Azure SQL DB
* Azure SQL Managed Instance
